plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # "jekyll-optional-front-matter" not included
